name: NeoLoad Demo App Regression Test
on: workflow_dispatch
env:
  TEST_NAME: '"CI Pipeline performance regression test"'
  WORKSPACE_NAME: '"Default Workspace"'
  VERSION: '8.42'
jobs:
  nightly_build_demo_app:
    name: Nightly build demo application
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api_url: https://neoload-api-eu.saas.neotys.com/
            token: NLWEB_EU_TOKEN
          - api_url: https://neoload-api.saas.neotys.com/
            token: NLWEB_US_TOKEN
    steps:
      - name: "Install NeoLoad CLI"
        run: pip3 install -U neoload
      - name: "NeoLoad Login"
        run: neoload login --url ${{ matrix.api_url }} --workspace ${{ env.WORKSPACE_NAME }} ${{ secrets[matrix.token] }}
      - name: "NeoLoad run test"
        run: >
          neoload run 
          --external-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
          --external-url-label "Github Action Run ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --name "Demo app regression test - Github build ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --description "Example of CI performance regression job started from Github, targeting a specific user path in the demo application." 
          ${{ env.TEST_NAME }}
 
